### ISSUE TITLE
CSS Checklist: CSS Selectors

### ISSUE THREAD

**Issue by nakulnandhakumar** [nakulnandhakumar/sp23-cse110-lab3#5]
complete the CSS Selectors section
- [x] Class Selector (.class)
- [x] ID Selector (#id)
- [x] Universal Selector (*)
- [x] Element Selector (element) 
- [x] Attribute Selector (e.g. [attribute=foo])     
- [x] Pseudo-class Selector (e.g. p:hover)
- [x] Selector List (element, element)                   /* select multiple elements */
- [x] Descendant Combinator (element element)
- [x] Child Combinator (element > element)
- [x] General sibling combinator (element ~ element)
- [x] Adjacent sibling combinator (element + element)
- [x] Combining Two Selectors (element.class)
